# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-15 01:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('maxsize', models.IntegerField()),
                ('course_code', models.CharField(max_length=15)),
                ('type', models.CharField(max_length=50)),
                ('students', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
